spring:
  profiles:
    active: local
    group:
      local: local
      blue: blue
      green: green

server:
  env: blue

---

spring:
  config:
    activate:
      on-profile: local

server:
  port: 8080
  address: localhost

serverName: local_server

---

spring:
  config:
    activate:
      on-profile: blue

server:
  port: 8080
  address: 43.203.85.172

serverName: blue_server

---

spring:
  config:
    activate:
      on-profile: green

server:
  port: 8081
  address: 43.203.85.172

serverName: green_server

---