spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error