spring:
  profiles:
    active: prod

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error